export const PRIVACY_POLICY_VERSION = '1.0.0';
export const PRIVACY_POLICY_TYPE = 'privacy_policy';

export const RESERVATION_EXPIRATION_MS = 15 * 60 * 1000;
export const RESERVATION_EXPIRATION_CRON_MS = 5 * 60 * 1000;
export const RESERVATION_EXPIRATION_PROVIDER = 20 * 60 * 1000;
